apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ir9xltio5-python 
  janus-idp.io/tekton: ir9xltio5-python
  backstage.io/kubernetes-id: ir9xltio5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ir9xltio5-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml