apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ir9xltio5-python-gitops
  description: This is GitOps manifest for ir9xltio5-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ir9xltio5-python
    backstage.io/kubernetes-id: ir9xltio5-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ir9xltio5-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ir9xltio5-python
